CREATE INDEX FirstNameIndex ON PERSONS(FIRST_NAME) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX LastNameIndex ON PERSONS(LAST_NAME) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX DiagnosisIndex ON RADIOLOGY_RECORD(DIAGNOSIS) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX DescriptionIndex ON RADIOLOGY_RECORD(DESCRIPTION) INDEXTYPE IS CTXSYS.CONTEXT;

CREATE SEQUENCE person_id_sequence
  START WITH (SELECT MAX(PERSON_ID)+1 FROM PERSONS);
  
CREATE SEQUENCE record_id_sequence
  START WITH (SELECT MAX(RECORD_ID)+1 FROM RADIOLOGY_RECORD);
  
CREATE SEQUENCE pic_id_sequence
  START WITH (SELECT MAX(IMAGE_ID)+1 FROM PACS_IMAGES);